class Food {
  // properties
  String name;
  String description;
  List<String> images;
  Map<String, String> chef;
  String timeToPrepare;
  String difficulty;
  double rating;
  String countryOfOrigin;
  int servingSize;
  String category;
  List<String> ingredients;
  List<String> steps;
  bool isSaved;

  // constructor
  Food({
    required this.name,
    required this.description,
    required this.images,
    required this.chef,
    required this.rating,
    required this.countryOfOrigin,
    required this.ingredients,
    required this.servingSize,
    required this.steps,
    required this.difficulty,
    required this.isSaved,
    required this.timeToPrepare,
    required this.category,
  });
}

// Create a list of food items
List<Food> foods = [
  Food(
    name: "Chicken Biryani",
    description:
        "A traditional and flavorful Pakistani rice dish made with chicken, aromatic spices, and basmati rice, commonly served at celebrations and gatherings.",
    images: [
      "https://images.pexels.com/photos/28674660/pexels-photo-28674660.jpeg",
      "https://images.pexels.com/photos/28674661/pexels-photo-28674661.jpeg",
      "https://images.pexels.com/photos/28674662/pexels-photo-28674662.jpeg",
      "https://images.pexels.com/photos/28674663/pexels-photo-28674663.jpeg",
      "https://images.pexels.com/photos/28674664/pexels-photo-28674664.jpeg",
    ],
    chef: {"name": "Chef Zubaida Tariq", "specialty": "Pakistani Cuisine"},
    timeToPrepare: "1 hour 30 minutes",
    difficulty: "Intermediate",
    rating: 4.8,
    countryOfOrigin: "Pakistan",
    servingSize: 6,
    category: "Main Course",
    ingredients: [
      "1 kg chicken, cut into pieces",
      "2 cups basmati rice",
      "2 large onions, thinly sliced",
      "1 cup yogurt",
      "2 large tomatoes, chopped",
      "4 green chilies, slit",
      "1/2 cup cooking oil",
      "1/4 cup milk",
      "1 tsp saffron strands",
      "Whole spices (cloves, cinnamon, bay leaves, cardamom)",
      "2 tsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "2 tsp garam masala",
      "1/4 cup fresh coriander leaves, chopped",
      "1/4 cup fresh mint leaves, chopped",
      "Salt to taste",
    ],
    steps: [
      "Wash and soak the basmati rice for 30 minutes.",
      "Heat oil in a large pot, fry the onions until golden brown, and set aside half for garnishing.",
      "Add the whole spices, ginger-garlic paste, and chicken to the remaining onions in the pot. Cook until the chicken is browned.",
      "Mix in the yogurt, tomatoes, green chilies, turmeric powder, red chili powder, and salt. Cook until the oil separates.",
      "Boil the soaked rice until 70% cooked, then drain and set aside.",
      "Layer the rice over the chicken mixture, sprinkle with garam masala, saffron milk, coriander, and mint leaves.",
      "Cover the pot with a tight-fitting lid and cook on low heat (dum) for 20-25 minutes.",
      "Mix gently before serving, ensuring the layers remain intact.",
      "Garnish with the reserved fried onions and serve hot with raita or salad.",
    ],
    isSaved: true,
  ),
  Food(
    name: "Beef Nihari",
    description:
        "A rich and flavorful slow-cooked beef stew made with aromatic spices, traditionally served with naan or parathas. It's a beloved Pakistani breakfast dish, especially on weekends.",
    images: [
      "https://images.unsplash.com/photo-1644364935906-792b2245a2c0",
      "https://images.unsplash.com/photo-1644364935915-f91f7a3962af",
      "https://images.pexels.com/photos/5410424/pexels-photo-5410424.jpeg",
      "https://images.pexels.com/photos/7353380/pexels-photo-7353380.jpeg",
      "https://images.pexels.com/photos/6260921/pexels-photo-6260921.jpeg",
    ],
    chef: {
      "name": "Chef Gulzar Hussain",
      "specialty": "Traditional Pakistani Dishes",
    },
    timeToPrepare: "4 hours",
    difficulty: "Advanced",
    rating: 3,
    countryOfOrigin: "Pakistan",
    servingSize: 4,
    category: "Main Course",
    ingredients: [
      "1 kg beef shank or stew meat, cut into pieces",
      "1 cup wheat flour",
      "1/2 cup cooking oil or ghee",
      "2 medium onions, thinly sliced",
      "2 tbsp ginger-garlic paste",
      "2 tsp red chili powder",
      "1 tsp turmeric powder",
      "1 tsp coriander powder",
      "1/2 tsp fennel seeds (saunf), ground",
      "1/2 tsp cumin seeds, ground",
      "1/4 tsp nutmeg powder",
      "1/4 tsp mace powder",
      "2 tbsp nihari spice mix (store-bought or homemade)",
      "8 cups water",
      "Salt to taste",
      "Fresh coriander leaves, chopped (for garnish)",
      "Ginger, julienned (for garnish)",
      "Lemon wedges (for serving)",
    ],
    steps: [
      "Heat oil or ghee in a large pot and fry the sliced onions until golden brown. Remove half for garnish and keep aside.",
      "Add ginger-garlic paste to the pot and sauté for a minute.",
      "Add the beef pieces and cook until browned.",
      "Mix in red chili powder, turmeric powder, coriander powder, nihari spice mix, and salt. Cook for 5 minutes.",
      "Add water and bring to a boil. Lower the heat and let the beef simmer for 3-4 hours until tender.",
      "Mix wheat flour with 1 cup of water to make a smooth paste. Gradually add this to the pot while stirring to avoid lumps. Let the curry thicken.",
      "Add fennel, cumin, nutmeg, and mace powders. Simmer for another 15 minutes.",
      "Garnish with the fried onions, fresh coriander leaves, and ginger juliennes.",
      "Serve hot with naan, paratha, or plain boiled rice, along with lemon wedges.",
    ],
    isSaved: true,
  ),
  Food(
    name: "Seekh Kebab",
    description:
        "Grilled minced meat skewers flavored with aromatic herbs and spices, commonly served as an appetizer or main course with mint chutney and naan.",
    images: [
      "https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg",
      "https://images.pexels.com/photos/2233730/pexels-photo-2233730.jpeg",
      "https://images.pexels.com/photos/2233731/pexels-photo-2233731.jpeg",
      "https://images.pexels.com/photos/2233732/pexels-photo-2233732.jpeg",
      "https://images.pexels.com/photos/2233733/pexels-photo-2233733.jpeg",
    ],
    chef: {
      "name": "Chef Tahir Chaudhry",
      "specialty": "Pakistani Grilled Cuisine",
    },
    timeToPrepare: "40 minutes",
    difficulty: "Medium",
    rating: 4.5,
    countryOfOrigin: "Pakistan",
    servingSize: 4,
    category: "Appetizer",
    ingredients: [
      "500g ground beef or mutton",
      "1 medium onion, finely chopped",
      "2 tbsp ginger-garlic paste",
      "2 green chilies, finely chopped",
      "1/4 cup fresh coriander leaves, chopped",
      "1/4 cup fresh mint leaves, chopped",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "1 tsp red chili powder",
      "1/2 tsp black pepper",
      "1 egg (for binding)",
      "Salt to taste",
      "2 tbsp lemon juice",
      "2 tbsp oil for basting",
    ],
    steps: [
      "In a large bowl, mix the ground meat with chopped onions, ginger-garlic paste, green chilies, fresh herbs, and all the spices.",
      "Add the egg and mix well to bind the mixture. Let it marinate for at least 30 minutes.",
      "Divide the mixture into equal portions and mold each portion onto skewers, pressing firmly to shape them into kebabs.",
      "Preheat a grill or a heavy-bottomed pan over medium heat.",
      "Brush the kebabs with oil and grill for 8-10 minutes, turning occasionally, until they're cooked through and have nice grill marks.",
      "Sprinkle with lemon juice before serving.",
      "Serve hot with mint chutney, sliced onions, and naan bread.",
    ],
    isSaved: false,
  ),
  Food(
    name: "Chapli Kebab",
    description:
        "Flat, round spicy patties of minced meat, originating from the Pashtun tribes of Peshawar. Known for their distinct flavor from a combination of pomegranate seeds, tomatoes, and various spices.",
    images: [
      "https://images.pexels.com/photos/1251198/pexels-photo-1251198.jpeg",
      "https://images.pexels.com/photos/1251199/pexels-photo-1251199.jpeg",
      "https://images.pexels.com/photos/1251200/pexels-photo-1251200.jpeg",
      "https://images.pexels.com/photos/1251201/pexels-photo-1251201.jpeg",
      "https://images.pexels.com/photos/1251202/pexels-photo-1251202.jpeg",
    ],
    chef: {"name": "Chef Sohail Ahmad", "specialty": "Pashtun Cuisine"},
    timeToPrepare: "35 minutes",
    difficulty: "Medium",
    rating: 4.6,
    countryOfOrigin: "Pakistan",
    servingSize: 5,
    category: "Main Course",
    ingredients: [
      "500g ground beef (preferably with fat)",
      "1 large onion, finely chopped",
      "2 tomatoes, finely chopped",
      "2 tbsp dried pomegranate seeds, crushed",
      "1 tbsp coriander seeds, crushed",
      "4 green chilies, chopped",
      "2 tbsp fresh coriander leaves, chopped",
      "2 tsp cumin seeds",
      "1 tsp garam masala",
      "1 tsp red chili flakes",
      "1 tsp dried mint leaves",
      "1 egg",
      "Salt to taste",
      "Cooking oil for frying",
    ],
    steps: [
      "In a large bowl, mix the ground beef with all the ingredients except the oil. Mix well and let it rest for 15 minutes.",
      "Divide the mixture into equal portions and shape them into flat, round patties about 1/2 inch thick.",
      "Press a small depression in the center of each patty with your thumb to prevent it from puffing up while cooking.",
      "Heat oil in a large frying pan over medium heat.",
      "Carefully place the kebabs in the hot oil and cook for 3-4 minutes on each side until they are browned and cooked through.",
      "Drain on paper towels to remove excess oil.",
      "Serve hot with naan, chutney, and fresh salad.",
    ],
    isSaved: true,
  ),
  Food(
    name: "Haleem",
    description:
        "A hearty stew made of wheat, lentils, and meat slow-cooked to a paste-like consistency. Popular during Ramadan and known for its rich flavor and nutritional value.",
    images: [
      "https://images.pexels.com/photos/7625056/pexels-photo-7625056.jpeg",
      "https://images.pexels.com/photos/7625057/pexels-photo-7625057.jpeg",
      "https://images.pexels.com/photos/7625058/pexels-photo-7625058.jpeg",
      "https://images.pexels.com/photos/7625059/pexels-photo-7625059.jpeg",
      "https://images.pexels.com/photos/7625060/pexels-photo-7625060.jpeg",
    ],
    chef: {
      "name": "Chef Mehboob Khan",
      "specialty": "Traditional Pakistani Slow-cooked Dishes",
    },
    timeToPrepare: "5 hours",
    difficulty: "Hard",
    rating: 4.7,
    countryOfOrigin: "Pakistan",
    servingSize: 8,
    category: "Main Course",
    ingredients: [
      "500g beef or mutton, cubed",
      "1 cup wheat, soaked overnight",
      "1/4 cup chana dal (split chickpeas), soaked",
      "1/4 cup masoor dal (red lentils), soaked",
      "1/4 cup moong dal (green gram), soaked",
      "2 large onions, sliced",
      "2 tbsp ginger-garlic paste",
      "2 tbsp haleem masala",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "1/2 tsp cinnamon powder",
      "1/2 tsp cumin powder",
      "1/4 cup cooking oil or ghee",
      "Salt to taste",
      "Fresh ginger, julienned (for garnish)",
      "Fresh lemon wedges",
      "Chopped coriander leaves (for garnish)",
      "Fried onions (for garnish)",
    ],
    steps: [
      "In a large pot, cook the meat with half of the ginger-garlic paste, some salt, and enough water to cover it. Cook until the meat is tender, about 2 hours.",
      "In another pot, cook the soaked wheat and lentils with turmeric and salt until soft and mushy, about 1.5 hours.",
      "Once the meat is tender, shred it either by pulsing in a food processor or using two forks.",
      "Heat oil in a large, heavy-bottomed pot. Fry the sliced onions until golden brown. Remove half for garnish and set aside.",
      "Add the remaining ginger-garlic paste to the pot and sauté for a minute.",
      "Add haleem masala, red chili powder, cinnamon, and cumin. Sauté for 2-3 minutes.",
      "Add the shredded meat, cooked wheat, and lentils to the pot. Mix well.",
      "Cook on low heat for another hour, stirring occasionally to prevent sticking. Add more water if it becomes too thick.",
      "The haleem should have a smooth, paste-like consistency when done.",
      "Serve hot, garnished with fried onions, julienned ginger, chopped coriander, and lemon wedges.",
    ],
    isSaved: false,
  ),
  Food(
    name: "Karahi Gosht",
    description:
        "A spicy meat dish cooked in a wok-like utensil called karahi, featuring tender meat pieces in a rich tomato and green chili base, popular in both Pakistan and northern India.",
    images: [
      "https://images.pexels.com/photos/8969237/pexels-photo-8969237.jpeg",
      "https://images.pexels.com/photos/8969238/pexels-photo-8969238.jpeg",
      "https://images.pexels.com/photos/8969239/pexels-photo-8969239.jpeg",
      "https://images.pexels.com/photos/8969240/pexels-photo-8969240.jpeg",
      "https://images.pexels.com/photos/8969241/pexels-photo-8969241.jpeg",
    ],
    chef: {"name": "Chef Rahat Ali", "specialty": "North Pakistani Cuisine"},
    timeToPrepare: "55 minutes",
    difficulty: "Medium",
    rating: 4.6,
    countryOfOrigin: "Pakistan",
    servingSize: 4,
    category: "Main Course",
    ingredients: [
      "750g mutton or chicken, cut into pieces",
      "4 large tomatoes, chopped",
      "8-10 green chilies, slit lengthwise",
      "1 large onion, finely chopped",
      "2 tbsp ginger, julienned",
      "2 tbsp garlic, minced",
      "1 tsp red chili powder",
      "1 tsp coriander powder",
      "1/2 tsp black pepper",
      "1/2 cup cooking oil or ghee",
      "1 tsp cumin seeds",
      "1 tbsp crushed coriander seeds",
      "Salt to taste",
      "Fresh coriander leaves, chopped",
      "2 tbsp yogurt (optional)",
    ],
    steps: [
      "Heat oil in a karahi or a deep frying pan. Add the meat pieces and sauté on high heat until they change color.",
      "Add chopped onions and fry until translucent.",
      "Add minced garlic and half of the julienned ginger. Cook for 2 minutes.",
      "Add chopped tomatoes, green chilies, red chili powder, coriander powder, and salt. Mix well.",
      "Cover and cook on medium heat for about 30 minutes, or until the meat is tender and the oil separates from the gravy.",
      "If using yogurt, add it now and mix well. Cook for an additional 5 minutes.",
      "Garnish with remaining julienned ginger, fresh coriander leaves, and slit green chilies.",
      "Serve hot with naan, roti, or rice.",
    ],
    isSaved: true,
  ),
  Food(
    name: "Gajar Ka Halwa",
    description:
        "A traditional Pakistani dessert made from carrots, milk, sugar, and ghee, slow-cooked to perfection. It's especially popular during winter seasons and festive occasions.",
    images: [
      "https://images.pexels.com/photos/90894/pexels-photo-90894.jpeg",
      "https://images.pexels.com/photos/90895/pexels-photo-90895.jpeg",
      "https://images.pexels.com/photos/90896/pexels-photo-90896.jpeg",
      "https://images.pexels.com/photos/90897/pexels-photo-90897.jpeg",
      "https://images.pexels.com/photos/90898/pexels-photo-90898.jpeg",
    ],
    chef: {"name": "Chef Shireen Anwar", "specialty": "Pakistani Desserts"},
    timeToPrepare: "60 minutes",
    difficulty: "Easy",
    rating: 4.5,
    countryOfOrigin: "Pakistan",
    servingSize: 6,
    category: "Dessert",
    ingredients: [
      "1 kg carrots, peeled and grated",
      "1 liter full-fat milk",
      "1 cup sugar (adjust to taste)",
      "1/2 cup ghee (clarified butter)",
      "1/4 cup khoya (dried milk solids), crumbled",
      "1/4 cup mixed nuts (almonds, pistachios, cashews), chopped",
      "1 tsp cardamom powder",
      "A pinch of saffron strands (optional)",
      "2 tbsp raisins (optional)",
    ],
    steps: [
      "Heat ghee in a deep, heavy-bottomed pan. Add the grated carrots and sauté for about 5 minutes on medium heat.",
      "Pour in the milk and bring to a boil. Reduce heat and simmer, stirring occasionally, until the milk is reduced and the carrots are soft, about 30-35 minutes.",
      "Add sugar and continue to cook until the mixture thickens and most of the liquid evaporates, about 15 minutes.",
      "Mix in the khoya, cardamom powder, and saffron (if using). Cook for another 5 minutes.",
      "Add the chopped nuts and raisins, reserving some for garnish. Mix well and cook for an additional 2-3 minutes.",
      "Remove from heat and let it cool slightly.",
      "Serve warm or chilled, garnished with the reserved nuts.",
    ],
    isSaved: false,
  ),
];

//  final List<Food> foodItemList = [
//     Food(
//       name: "Chicken Biryani",
//       description:
//           "Fragrant rice dish with marinated chicken and aromatic spices",
//       imageUrl:
//           "https://images.pexels.com/photos/17649369/pexels-photo-17649369/free-photo-of-meat-with-rice.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//       timeToPrepare: "60 mins",
//       difficulty: "Medium",
//       rating: "4.8",
//       category: "Pakistani Cuisine",
//     ),
//     Food(
//       name: "Beef Nihari",
//       description:
//           "Slow-cooked beef stew with rich spicest",
//       imageUrl:
//           "https://images.pexels.com/photos/2313686/pexels-photo-2313686.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//       timeToPrepare: "180 mins",
//       difficulty: "Hard",
//       rating: "4.7",
//       category: "Pakistani Cuisine",
//     ),
//     Food(
//       name: "Seekh Kebab",
//       description: "Grilled minced meat skewers flavored with herbs and spices",
//       imageUrl:
//           "https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//       timeToPrepare: "40 mins",
//       difficulty: "Medium",
//       rating: "4.5",
//       category: "Pakistani Cuisine",
//     ),
//     Food(
//       name: "Chapli Kebab",
//       description: "Spicy minced meat patties famous in Peshawar region",
//       imageUrl:
//           "https://images.pexels.com/photos/1251198/pexels-photo-1251198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//       timeToPrepare: "30 mins",
//       difficulty: "Medium",
//       rating: "4.6",
//       category: "Pakistani Cuisine",
//     ),
//     Food(
//       name: "Haleem",
//       description:
//           "Slow-cooked stew of wheat, lentils, and meat",
//       imageUrl:
//           "https://images.pexels.com/photos/7625056/pexels-photo-7625056.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//       timeToPrepare: "150 mins",
//       difficulty: "Hard",
//       rating: "4.7",
//       category: "Pakistani Cuisine",
//     ),
//     Food(
//       name: "Karahi Gosht",
//       description: "Spicy meat dish cooked in a wok-like utensil called karahi",
//       imageUrl:
//           "https://images.pexels.com/photos/8969237/pexels-photo-8969237.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//       timeToPrepare: "45 mins",
//       difficulty: "Medium",
//       rating: "4.6",
//       category: "Pakistani Cuisine",
//     ),
//     Food(
//       name: "Aloo Keema",
//       description: "Minced meat cooked with potatoes and traditional spices",
//       imageUrl:
//           "https://images.pexels.com/photos/7211169/pexels-photo-7211169.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//       timeToPrepare: "40 mins",
//       difficulty: "Easy",
//       rating: "4.3",
//       category: "Pakistani Cuisine",
//     ),
//     Food(
//       name: "Chana Chaat",
//       description: "Tangy chickpea salad with vegetables and tamarind sauce",
//       imageUrl:
//           "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//       timeToPrepare: "20 mins",
//       difficulty: "Easy",
//       rating: "4.2",
//       category: "Pakistani Cuisine",
//     ),
//     Food(
//       name: "Paya Soup",
//       description: "Traditional soup made from slow-cooking trotters in spices",
//       imageUrl:
//           "https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//       timeToPrepare: "240 mins",
//       difficulty: "Hard",
//       rating: "4.4",
//       category: "Pakistani Cuisine",
//     ),
//     Food(
//       name: "Sheermal",
//       description:
//           "Saffron-flavored traditional flatbread, often served with kebabs",
//       imageUrl:
//           "https://images.pexels.com/photos/1586942/pexels-photo-1586942.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//       timeToPrepare: "35 mins",
//       difficulty: "Medium",
//       rating: "4.1",
//       category: "Pakistani Cuisine",
//     ),
//   ];
